#References:
# Samples Database From: https://www.usabledatabases.com/database/books-isbn-covers/sample/#table_book

# WARNING: DO NOT EDIT THIS FILE

import csv
from random import randint

book_list = []
header = []

def getHeader():
    return header

def getRandomBook():
    num = randint(1,len(book_list)-1)
    return book_list[num]

def getRandomBookList(numBooks):
    num = randint(0,len(book_list)-1-numBooks)
    new_list = []
    for i in range(num, num+numBooks):
        new_list.append(book_list[i])
    return new_list

def readDatabase():
    line_count = 0
    with open('book-database.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            if line_count == 0:
                row.remove(row[0])
                for element in row:
                    header.append(element)
                line_count += 1
            else:
                row.remove(row[0])
                book_list.append(row)
                line_count += 1
    return line_count

if __name__ == "__main__":
    print('Processed {0} lines.'.format(readDatabase()))
    print(f'Column names are {", ".join(header)}.')
    print(getRandomBook())
else:
    readDatabase()
